# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app
ENV TERM xterm

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install
RUN apt-get install -y procps

# Copy the rest of the application code to the container
COPY . .

# Expose the port that your Node.js server is listening on
EXPOSE 1337

# Start your Node.js server
CMD ["node", "index.js"]
